version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file photoAppTemplate.yaml --s3-bucket lambdapipeline-album --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - photoAppTemplate.yaml
    - outputsamtemplate.yml
